{% set name = "sensormapgeo" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sensormapgeo-{{ version }}.tar.gz
  sha256: ed5a07e644bdef0faeb8ed53c540954489131cc6e2038a27bb20a1f23b01029b

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools
  run:
    - gdal >=3.8
    - joblib
    - numpy
    - py-tools-ds >=0.18.0
    - pyproj >=2.2
    - pyresample >=1.17.0
    - python

test:
  imports:
    - sensormapgeo
    - sensormapgeo.transformer
    - sensormapgeo.gdal_backend.transformer_2d
    - sensormapgeo.gdal_backend.transformer_3d
    - sensormapgeo.pyresample_backend.transformer_2d
    - sensormapgeo.pyresample_backend.transformer_3d
    - sensormapgeo.transformer_2d
    - sensormapgeo.transformer_3d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz-potsdam.de/EnMAP/sensormapgeo
  summary: A package for transforming remote sensing images between sensor and map geometry.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
